### ISSUE TITLE
Warning "Illegal reflective access by org.mockito.cglib.core.ReflectUtil$2"

### ISSUE THREAD

**Issue by lca-afi** [mockito/mockito-cglib#1]
Hi there,

we are currently migrating from Java 8 to OpenJDK 11. During our maven build we get the following warning:

Illegal reflective access by org.mockito.cglib.core.ReflectUtils$2 (file:/app/jenkins/workspace/.*/org.mockito/1.9.5/org.mockito-1.9.5.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,in$ 
Please consider reporting this to the maintainers of org.mockito.cglib.core.ReflectUtils$2$/

What's the problem here, and does anyone see a possibility to solve this in the near future?

Kind Regards,
Alex

**Comment by bric3** [comment]
Hi,

Thanks for reaching out, mockito-cglib is mostly an extracted version of the old mockmaker in case someone needs CGLIB and wants wants to contribute to this version of the mock-maker.

I see from the posted stack that it's running mockito 1.9.5 -- it's a pretty old version -- it's been quite a long time since we released version 2. Mockito is now at 2.23.4 and it now uses ByteBuddy to generates mocks. And JDK 11 is fully supported starting 2.23.
